<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Confirm</strong> deleting' => '<strong>Confirmar</strong> borrado',
    'Add Task' => 'Añadir Tarea',
    'Cancel' => 'Cancelar',
    'Delete' => 'Borrar',
    'Do you really want to delete this task?' => '¿Estás seguro/a de que quieres borrar esta tarea?',
    'No open tasks...' => 'No hay tareas abiertas...',
    'completed tasks' => 'tareas completadas',
];
