FROM codemix/yii2-base:2.0.8-php7-apache
#FROM codemix/yii2-base:2.0.8-php7-fpm
#FROM codemix/yii2-base:2.0.8-hhvm


# Composer packages are installed first. This will only add packages
# that are not already in the yii2-base image.
COPY composer.json /var/www/html/
COPY composer.lock /var/www/html/
# Install needed php extensions: ldap
RUN \
  apt-get update && \
  apt-get install libldap2-dev -y && \
  rm -rf /var/lib/apt/lists/* && \
  docker-php-ext-configure ldap --with-libdir=lib/x86_64-linux-gnu/ && \
  docker-php-ext-install ldap \
  && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
  
# GD
RUN apt-get update && \
  apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng12-dev --no-install-recommends \
  && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
  && docker-php-ext-install gd \
  && docker-php-ext-install exif \
  && rm -rf /var/lib/apt/lists/* && rm -rf /tmp/*
  
RUN composer self-update --no-progress && \
    composer install --no-progress

# Copy the working dir to the image's web root
COPY . /var/www/html

# The following directories are .dockerignored to not pollute the docker images
# with local logs and published assets from development. So we need to create
# empty dirs and set right permissions inside the container.
RUN mkdir runtime \
    && chown www-data:www-data runtime web/assets

# Expose everything under /var/www (vendor + html)
# This is only required for the nginx setup
VOLUME ["/var/www"]
